import React, { useState, useEffect } from 'react';
import {
  Drawer,
  Box,
  Typography,
  TextField,
  List,
  ListItem,
  ListItemButton,
  ListItemText,
  ListItemIcon,
  Chip,
  Alert,
  CircularProgress,
  Divider,
  IconButton,
  InputAdornment,
  Tabs,
  Tab,
  Badge,
} from '@mui/material';
import { Close, Search, Warning, CheckCircle, ErrorOutline, Info, Code } from '@mui/icons-material';
import api from '../../utils/apiShim';
import HelpIcon from './HelpIcon';

/**
 * HelpDrawer Component
 *
 * Comprehensive help browser that shows all available actions.
 * Supports search, filtering, and highlights unmapped actions.
 *
 * Usage:
 *   const [helpOpen, setHelpOpen] = useState(false);
 *   <HelpDrawer open={helpOpen} onClose={() => setHelpOpen(false)} />
 */
export default function HelpDrawer({ open, onClose }) {
  const [registry, setRegistry] = useState([]);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState(null);
  const [searchQuery, setSearchQuery] = useState('');
  const [selectedTab, setSelectedTab] = useState(0);
  const [selectedAction, setSelectedAction] = useState(null);

  useEffect(() => {
    if (open && registry.length === 0) {
      fetchRegistry();
    }
  }, [open]);

  const fetchRegistry = async () => {
    setLoading(true);
    setError(null);

    try {
      const response = await api.get('/api/help/registry');

      if (!response.data.success) {
        throw new Error(response.data.message || 'Failed to load help registry');
      }

      setRegistry(response.data.actions || []);
    } catch (err) {
      console.error('Failed to fetch help registry:', err);
      setError(err.message);
    } finally {
      setLoading(false);
    }
  };

  // Categorize actions
  const categorizedActions = {
    all: registry,
    documented: registry.filter((a) => !a.inferred && !a.needs_backend),
    needsBackend: registry.filter((a) => a.needs_backend),
    autogenerated: registry.filter((a) => a.inferred),
    dangerous: registry.filter((a) => {
      const dangerKeywords = ['delete', 'kill', 'emergency', 'force', 'destroy', 'live'];
      return (
        dangerKeywords.some((kw) => a.action_id.toLowerCase().includes(kw)) ||
        (a.risks && a.risks.length > 0)
      );
    }),
  };

  // Filter actions based on search
  const filteredActions = categorizedActions[
    ['all', 'documented', 'needsBackend', 'autogenerated', 'dangerous'][selectedTab]
  ].filter(
    (action) =>
      !searchQuery ||
      action.action_id.toLowerCase().includes(searchQuery.toLowerCase()) ||
      action.title.toLowerCase().includes(searchQuery.toLowerCase()) ||
      action.summary.toLowerCase().includes(searchQuery.toLowerCase())
  );

  const getActionIcon = (action) => {
    if (action.needs_backend) return <ErrorOutline color="warning" />;
    if (action.inferred) return <Info color="info" />;
    if (action.risks && action.risks.length > 0) return <Warning color="error" />;
    return <CheckCircle color="success" />;
  };

  const getActionBadge = (action) => {
    if (action.needs_backend) return <Chip label="No Backend" size="small" color="warning" />;
    if (action.inferred) return <Chip label="Auto-generated" size="small" color="info" />;
    if (action.risks && action.risks.length > 0)
      return <Chip label="Dangerous" size="small" color="error" />;
    return null;
  };

  return (
    <Drawer
      anchor="right"
      open={open}
      onClose={onClose}
      PaperProps={{
        sx: {
          width: { xs: '100%', sm: 600 },
          maxWidth: '100vw',
        },
      }}
    >
      <Box sx={{ height: '100%', display: 'flex', flexDirection: 'column' }}>
        {/* Header */}
        <Box sx={{ p: 2, borderBottom: 1, borderColor: 'divider' }}>
          <Box
            sx={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', mb: 2 }}
          >
            <Typography variant="h5" sx={{ fontWeight: 'bold' }}>
              ❓ Help Center
            </Typography>
            <IconButton onClick={onClose}>
              <Close />
            </IconButton>
          </Box>

          {/* Search */}
          <TextField
            fullWidth
            size="small"
            placeholder="Search actions..."
            value={searchQuery}
            onChange={(e) => setSearchQuery(e.target.value)}
            InputProps={{
              startAdornment: (
                <InputAdornment position="start">
                  <Search />
                </InputAdornment>
              ),
            }}
          />

          {/* Tabs */}
          <Tabs
            value={selectedTab}
            onChange={(e, newValue) => setSelectedTab(newValue)}
            variant="scrollable"
            scrollButtons="auto"
            sx={{ mt: 2 }}
          >
            <Tab label={`All (${categorizedActions.all.length})`} />
            <Tab
              label={
                <Badge badgeContent={categorizedActions.documented.length} color="success">
                  Documented
                </Badge>
              }
            />
            <Tab
              label={
                <Badge badgeContent={categorizedActions.needsBackend.length} color="warning">
                  Needs Backend
                </Badge>
              }
            />
            <Tab
              label={
                <Badge badgeContent={categorizedActions.autogenerated.length} color="info">
                  Auto-gen
                </Badge>
              }
            />
            <Tab
              label={
                <Badge badgeContent={categorizedActions.dangerous.length} color="error">
                  Dangerous
                </Badge>
              }
            />
          </Tabs>
        </Box>

        {/* Content */}
        <Box sx={{ flex: 1, overflow: 'auto' }}>
          {loading ? (
            <Box sx={{ display: 'flex', justifyContent: 'center', alignItems: 'center', p: 4 }}>
              <CircularProgress />
            </Box>
          ) : error ? (
            <Alert severity="error" sx={{ m: 2 }}>
              {error}
            </Alert>
          ) : filteredActions.length === 0 ? (
            <Alert severity="info" sx={{ m: 2 }}>
              No actions found matching "{searchQuery}"
            </Alert>
          ) : (
            <List>
              {filteredActions.map((action, idx) => (
                <React.Fragment key={action.action_id}>
                  <ListItemButton
                    onClick={() =>
                      setSelectedAction(
                        selectedAction?.action_id === action.action_id ? null : action
                      )
                    }
                  >
                    <ListItemIcon>{getActionIcon(action)}</ListItemIcon>
                    <ListItemText
                      primary={
                        <Box sx={{ display: 'flex', alignItems: 'center', gap: 1 }}>
                          <Typography variant="body1" sx={{ fontWeight: 'bold' }}>
                            {action.title}
                          </Typography>
                          {getActionBadge(action)}
                        </Box>
                      }
                      secondary={
                        <>
                          <Typography variant="body2" color="text.secondary" sx={{ mb: 0.5 }}>
                            {action.summary.substring(0, 100)}
                            {action.summary.length > 100 && '...'}
                          </Typography>
                          {action.api && action.api.path && (
                            <Chip
                              label={`${action.api.method} ${action.api.path}`}
                              size="small"
                              variant="outlined"
                              sx={{ mt: 0.5 }}
                            />
                          )}
                        </>
                      }
                    />
                  </ListItemButton>

                  {/* Expanded Details */}
                  {selectedAction?.action_id === action.action_id && (
                    <Box sx={{ px: 3, py: 2, bgcolor: 'action.hover' }}>
                      {/* Effects */}
                      {action.effects && action.effects.length > 0 && (
                        <Box sx={{ mb: 2 }}>
                          <Typography variant="subtitle2" sx={{ fontWeight: 'bold', mb: 1 }}>
                            What it does:
                          </Typography>
                          <List dense>
                            {action.effects.slice(0, 5).map((effect, i) => (
                              <ListItem key={i} sx={{ pl: 0 }}>
                                <ListItemText
                                  primary={`• ${effect}`}
                                  primaryTypographyProps={{ variant: 'body2' }}
                                />
                              </ListItem>
                            ))}
                          </List>
                        </Box>
                      )}

                      {/* Related Config */}
                      {action.related_config && action.related_config.length > 0 && (
                        <Box sx={{ mb: 2 }}>
                          <Typography variant="subtitle2" sx={{ fontWeight: 'bold', mb: 1 }}>
                            Related Config:
                          </Typography>
                          {action.related_config.map((config, i) => (
                            <Chip
                              key={i}
                              label={`${config.key}=${config.value}`}
                              size="small"
                              variant="outlined"
                              sx={{ mr: 0.5, mb: 0.5 }}
                            />
                          ))}
                        </Box>
                      )}

                      {/* Risks */}
                      {action.risks && action.risks.length > 0 && (
                        <Box sx={{ mb: 2 }}>
                          <Typography
                            variant="subtitle2"
                            sx={{ fontWeight: 'bold', mb: 1, color: 'error.main' }}
                          >
                            ⚠️ Risks:
                          </Typography>
                          {action.risks.map((risk, i) => (
                            <Alert key={i} severity="warning" sx={{ mb: 1 }}>
                              <Typography variant="body2">{risk}</Typography>
                            </Alert>
                          ))}
                        </Box>
                      )}

                      {/* Code References */}
                      {action.code_refs && action.code_refs.length > 0 && (
                        <Box>
                          <Typography variant="subtitle2" sx={{ fontWeight: 'bold', mb: 1 }}>
                            <Code fontSize="small" sx={{ mr: 0.5 }} />
                            Code References:
                          </Typography>
                          {action.code_refs.map((ref, i) => (
                            <Typography
                              key={i}
                              variant="caption"
                              sx={{ display: 'block', fontFamily: 'monospace', mb: 0.5 }}
                            >
                              {ref}
                            </Typography>
                          ))}
                        </Box>
                      )}
                    </Box>
                  )}

                  {idx < filteredActions.length - 1 && <Divider />}
                </React.Fragment>
              ))}
            </List>
          )}
        </Box>

        {/* Footer */}
        <Box sx={{ p: 2, borderTop: 1, borderColor: 'divider', bgcolor: 'background.paper' }}>
          <Typography variant="caption" color="text.secondary">
            📊 {registry.length} total actions documented
          </Typography>
          {categorizedActions.needsBackend.length > 0 && (
            <Typography variant="caption" color="warning.main" sx={{ display: 'block' }}>
              ⚠️ {categorizedActions.needsBackend.length} actions need backend mapping
            </Typography>
          )}
          <Typography variant="caption" color="text.secondary" sx={{ display: 'block', mt: 1 }}>
            Press ? to open help for focused control
          </Typography>
        </Box>
      </Box>
    </Drawer>
  );
}
