-- Database Schema for WorkingBot Prototype
-- Created: January 30, 2026
-- Purpose: Store historical data for backtesting and optimization

-- OHLCV Data (Candlestick data for underlying assets)
CREATE TABLE IF NOT EXISTS ohlcv (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    symbol TEXT NOT NULL,
    timestamp INTEGER NOT NULL,  -- Unix timestamp
    open REAL NOT NULL,
    high REAL NOT NULL,
    low REAL NOT NULL,
    close REAL NOT NULL,
    volume REAL NOT NULL,
    timeframe TEXT NOT NULL,  -- '1m', '5m', '1h', '1d'
    created_at INTEGER DEFAULT (strftime('%s', 'now')),
    UNIQUE(symbol, timestamp, timeframe)
);

CREATE INDEX IF NOT EXISTS idx_ohlcv_symbol_time ON ohlcv(symbol, timestamp, timeframe);
CREATE INDEX IF NOT EXISTS idx_ohlcv_timestamp ON ohlcv(timestamp);

-- Options Chain Snapshots
CREATE TABLE IF NOT EXISTS options_chains (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    underlying_symbol TEXT NOT NULL,
    snapshot_timestamp INTEGER NOT NULL,
    contract_symbol TEXT NOT NULL,  -- e.g., 'BTCUSD-30JAN26-50000-P'
    strike REAL NOT NULL,
    expiry INTEGER NOT NULL,  -- Unix timestamp
    option_type TEXT NOT NULL CHECK(option_type IN ('call', 'put')),
    bid REAL,
    ask REAL,
    last_price REAL,
    mark_price REAL,
    iv REAL,  -- Implied volatility
    delta REAL,
    gamma REAL,
    theta REAL,
    vega REAL,
    rho REAL,
    volume INTEGER,
    open_interest INTEGER,
    underlying_price REAL,
    created_at INTEGER DEFAULT (strftime('%s', 'now')),
    UNIQUE(contract_symbol, snapshot_timestamp)
);

CREATE INDEX IF NOT EXISTS idx_options_underlying ON options_chains(underlying_symbol, snapshot_timestamp);
CREATE INDEX IF NOT EXISTS idx_options_expiry ON options_chains(expiry);
CREATE INDEX IF NOT EXISTS idx_options_strike ON options_chains(strike);

-- IV Rank/Percentile History
CREATE TABLE IF NOT EXISTS iv_history (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    symbol TEXT NOT NULL,
    timestamp INTEGER NOT NULL,
    current_iv REAL NOT NULL,
    iv_rank REAL,  -- 0-100
    iv_percentile REAL,  -- 0-100
    hv_10d REAL,  -- 10-day historical volatility
    hv_30d REAL,  -- 30-day historical volatility
    hv_60d REAL,
    created_at INTEGER DEFAULT (strftime('%s', 'now')),
    UNIQUE(symbol, timestamp)
);

CREATE INDEX IF NOT EXISTS idx_iv_symbol_time ON iv_history(symbol, timestamp);

-- Strategy Signals (Generated by algorithms)
CREATE TABLE IF NOT EXISTS signals (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    strategy_name TEXT NOT NULL,
    symbol TEXT NOT NULL,
    signal_time INTEGER NOT NULL,
    signal_type TEXT NOT NULL,  -- 'ENTRY', 'EXIT'
    action TEXT NOT NULL,  -- 'SELL_PUT', 'SELL_CALL', 'IRON_CONDOR', etc.
    confidence REAL,  -- 0.0 to 1.0
    reasoning TEXT,  -- Why this signal was generated
    metadata TEXT,  -- JSON with additional data
    created_at INTEGER DEFAULT (strftime('%s', 'now'))
);

CREATE INDEX IF NOT EXISTS idx_signals_strategy ON signals(strategy_name, signal_time);
CREATE INDEX IF NOT EXISTS idx_signals_symbol ON signals(symbol, signal_time);

-- Backtest Results
CREATE TABLE IF NOT EXISTS backtest_results (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    strategy_name TEXT NOT NULL,
    backtest_id TEXT NOT NULL,  -- UUID
    start_date INTEGER NOT NULL,
    end_date INTEGER NOT NULL,
    initial_capital REAL NOT NULL,
    final_capital REAL,
    total_return REAL,
    total_trades INTEGER,
    winning_trades INTEGER,
    losing_trades INTEGER,
    win_rate REAL,
    avg_win REAL,
    avg_loss REAL,
    largest_win REAL,
    largest_loss REAL,
    sharpe_ratio REAL,
    sortino_ratio REAL,
    max_drawdown REAL,
    profit_factor REAL,
    parameters TEXT,  -- JSON with strategy parameters
    created_at INTEGER DEFAULT (strftime('%s', 'now')),
    UNIQUE(backtest_id)
);

CREATE INDEX IF NOT EXISTS idx_backtest_strategy ON backtest_results(strategy_name);

-- Backtest Trades (Individual trades from backtests)
CREATE TABLE IF NOT EXISTS backtest_trades (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    backtest_id TEXT NOT NULL,
    trade_number INTEGER NOT NULL,
    entry_time INTEGER NOT NULL,
    exit_time INTEGER,
    symbol TEXT NOT NULL,
    trade_type TEXT NOT NULL,  -- 'LONG', 'SHORT', 'OPTION_SELL_PUT', etc.
    entry_price REAL NOT NULL,
    exit_price REAL,
    quantity REAL NOT NULL,
    pnl REAL,
    pnl_percent REAL,
    exit_reason TEXT,  -- 'TAKE_PROFIT', 'STOP_LOSS', 'SIGNAL', etc.
    metadata TEXT,  -- JSON with contract details, etc.
    FOREIGN KEY (backtest_id) REFERENCES backtest_results(backtest_id)
);

CREATE INDEX IF NOT EXISTS idx_trades_backtest ON backtest_trades(backtest_id);

-- Optimization Results
CREATE TABLE IF NOT EXISTS optimization_results (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    strategy_name TEXT NOT NULL,
    optimization_id TEXT NOT NULL,  -- UUID
    trial_number INTEGER NOT NULL,
    parameters TEXT NOT NULL,  -- JSON with parameters tested
    objective_value REAL NOT NULL,  -- Sharpe ratio or custom metric
    backtest_id TEXT,  -- Link to backtest
    created_at INTEGER DEFAULT (strftime('%s', 'now')),
    FOREIGN KEY (backtest_id) REFERENCES backtest_results(backtest_id)
);

CREATE INDEX IF NOT EXISTS idx_optimization_strategy ON optimization_results(strategy_name, optimization_id);
